PLAYER_LOGIN = "PLAYER_LOGIN"
PLAYER_LOGOUT = "PLAYER_LOGOUT"
BATTLE_START = "BATTLE_START"
BATTLE_END = "BATTLE_END"

EVENT_LABELS = {
    PLAYER_LOGIN: "login",
    PLAYER_LOGOUT: "logout",
    BATTLE_START: "battle_start",
    BATTLE_END: "battle_end",
}
